version: '3'

services:

    web1:
        container_name: service1
        build: ./web-static
        image: service1
        ports:
            - "9001:9000"        
 
    web2:
        container_name: service2
        build: ./web-ui
        image: service2
        ports:
            - "9002:9000"

    proxy:
        container_name: proxy
        build: ./nginx
        image: proxy
        ports:
            - "9000:80"